/*
 *    This file is part of the Map Link mod
 *    licensed under the GNU GPL v3 License.
 *    (some parts of this file are originally from the Distant Horizons mod by James Seibel)
 *
 *    Copyright (C) 2024 - 2026  Leander Knüttel and contributors
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * file changed by: Leander Knüttel
 * date: 06.08.2026
 */

plugins {
    id "net.fabricmc.fabric-loom" version "1.17.7" apply false
    id "net.fabricmc.fabric-loom-remap" version "1.17.7" apply false
}

if (rootProject.minecraft_version.startsWith("1")) {
    apply plugin: "net.fabricmc.fabric-loom-remap"
} else {
    apply plugin: "net.fabricmc.fabric-loom"
}

loom {
    accessWidenerPath = project(":common").file("src/main/resources/${accessWidenerVersion}.${mod_id}.accesswidener")

    mixin {
        useLegacyMixinAp = false
    }
    // "runs" isn't required, but when we do need it then it can be useful
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("../run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("../run")
        }
    }
}

mainJarTask().configure {
    if (it.hasProperty('inputFile')) {
        it.inputFile = shadowJar.archiveFile
    }
    else {
        from(zipTree(shadowJar.archiveFile)) {
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }
    }

    dependsOn shadowJar
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    if (rootProject.minecraft_version.startsWith("1.")) {
        mappings loom.layered() {
            // Mojmap mappings
            officialMojangMappings()
            // Parchment mappings (it adds parameter mappings & javadoc)
            parchment("org.parchmentmc.data:parchment-${rootProject.parchment_minecraft}:${rootProject.parchment_version}@zip")
        }
    }
    // Fabric loader
    modDep "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modDep "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    // Mod Menu
    if (rootProject.modmenu_version != "") {
        modDep("com.terraformersmc:modmenu:${rootProject.modmenu_version}") {
            exclude(group: "net.fabricmc")
        }
    }

    modApiDep("me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_api_fabric_version}") {
        exclude(group: "net.fabricmc")
    }

    if (rootProject.enable_xaeros_minimap == "true") {
        if (rootProject.hasProperty("xaeros_minimap_fabric_version") && rootProject.xaeros_minimap_fabric_version != "") {
            modDep "xaero.minimap:xaerominimap-fabric-${rootProject.minecraft_version}:${rootProject.xaeros_minimap_fabric_version}"
        } else {
            modDep "xaero.minimap:xaerominimap-fabric-${rootProject.minecraft_version}:${rootProject.default_xaeros_minimap_version}"
        }
    } else {
        if (rootProject.hasProperty("xaeros_minimap_fabric_version") && rootProject.xaeros_minimap_fabric_version != "") {
            modCompileDep "xaero.minimap:xaerominimap-fabric-${rootProject.minecraft_version}:${rootProject.xaeros_minimap_fabric_version}"
        } else {
            modCompileDep "xaero.minimap:xaerominimap-fabric-${rootProject.minecraft_version}:${rootProject.default_xaeros_minimap_version}"
        }
    }
    if (rootProject.enable_xaeros_worldmap == "true") {
        if (rootProject.hasProperty("xaeros_worldmap_fabric_version") && rootProject.xaeros_worldmap_fabric_version != "") {
            modDep "xaero.map:xaeroworldmap-fabric-${rootProject.minecraft_version}:${rootProject.xaeros_worldmap_fabric_version}"
        } else {
            modDep "xaero.map:xaeroworldmap-fabric-${rootProject.minecraft_version}:${rootProject.default_xaeros_worldmap_version}"
        }
    } else {
        if (rootProject.hasProperty("xaeros_worldmap_fabric_version") && rootProject.xaeros_worldmap_fabric_version != "") {
            modCompileDep "xaero.map:xaeroworldmap-fabric-${rootProject.minecraft_version}:${rootProject.xaeros_worldmap_fabric_version}"
        } else {
            modCompileDep "xaero.map:xaeroworldmap-fabric-${rootProject.minecraft_version}:${rootProject.default_xaeros_worldmap_version}"
        }
    }
    modCompileDep "xaero.lib:xaerolib-fabric-${rootProject.minecraft_version}:${rootProject.xaero_lib_version}"
}

tasks.register('deleteResources', Delete) {
    delete file("build/resources/main")
}

processResources {
    dependsOn(tasks.named("copyCoreResources"))
    dependsOn(tasks.named("copyCommonLoaderResources"))
    exclude "*.accesstransformer.cfg"
}

runClient {
    dependsOn(copyCoreResources)
    dependsOn(copyCommonLoaderResources)
    //jvmArgs([ minecraftMemoryJavaArg ])
    finalizedBy(deleteResources)
}

publishMods {
    file = mainJarTask().archiveFile
    dryRun = publish_debug_mode.toBoolean()
    changelog = file("$rootDir/docs/changelogs/${mod_version}.md").text.trim()
    version = mod_version
    switch (release_type) {
        case "alpha":
            type = ALPHA
            break
        case "beta":
            type = BETA
            break
        case "stable":
            type = STABLE
            break
    }
    boolean quiltCompatible
    if (rootProject.hasProperty("fabric_is_quilt_compatible")) {
        quiltCompatible = rootProject.fabric_is_quilt_compatible.toBoolean()
    }
    else {
        quiltCompatible = default_quilt_compatibility.toBoolean()
    }

    if (quiltCompatible) {
        displayName = "[Fabric & Quilt | ${rootProject.file_name}] ${mod_version}"
    }
    else {
        displayName = "[Fabric | ${rootProject.file_name}] ${mod_version}"
    }

    modLoaders.add("fabric")
    if (quiltCompatible) modLoaders.add("quilt")

    String gameVersionsString = rootProject.compatible_minecraft_versions
    String[] gameVersions = gameVersionsString.replace("[", "").replace("]", "").replaceAll(" ", "").replaceAll("\"", "").split(",")

    if (publish_to_modrinth.toBoolean()) {
        modrinth {
            accessToken = providers.environmentVariable("MODRINTH_TOKEN")
            projectId = modrinth_id
            minecraftVersions.addAll(gameVersions)

            requires("fabric-api", "cloth-config")
            optional("modmenu", "xaeros-minimap", "xaeros-minimap-fair", "xaeros-world-map")
        }
    }

    if (publish_to_curseforge.toBoolean()) {
        curseforge {
            accessToken = providers.environmentVariable("CURSE_TOKEN")
            projectId = curseforge_id
            if (curse_environment == "both" || curse_environment == "server") serverRequired = true
            if (curse_environment == "both" || curse_environment == "client") clientRequired = true
            minecraftVersions.addAll(gameVersions)

            requires("fabric-api", "cloth-config")
            optional("modmenu", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "xaeros-world-map")
        }
    }
}
