/*
 *    This file is part of the Map Link mod
 *    licensed under the GNU GPL v3 License.
 *    (some parts of this file are originally from the Distant Horizons mod by James Seibel)
 *
 *    Copyright (C) 2024 - 2026  Leander Knüttel and contributors
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * file changed by: Leander Knüttel
 * date: 06.08.2026
 */

plugins {
    id "java"

    // Plugin to put dependencies inside our final jar
    id "com.gradleup.shadow" version '9.6.1' apply false

    // Manifold preprocessor
    id "systems.manifold.manifold-gradle-plugin" version "0.0.2-alpha"

    id "me.modmuss50.mod-publish-plugin" version "2.1.0" apply false
}


/**
 * Creates the list of preprocessors to use.
 *
 * @param mcVers array of all MC versions
 * @param mcIndex array index of the currently active MC version
 */
def writeBuildGradlePredefine(List<String> mcVers, int mcIndex)
{
    // Build the list of preprocessors to use
    StringBuilder sb = new StringBuilder();

    sb.append("# DON'T TOUCH THIS FILE, This is handled by the build script\n");
    
    
    for (int i = 0; i < mcVers.size(); i++)
    {
        String verStr = mcVers[i].replace(".", "_");
        sb.append("MC_" + verStr + "=" + i.toString() + "\n");
        
        if (mcIndex == i)
            sb.append("MC_VER=" + i.toString() + "\n");
    }
    

    // Check if this is a development build
    if (mod_version.toLowerCase().contains("dev"))
    {
        // WARNING: only use this for logging, we don't want to have confusion
        // when a method doesn't work correctly in the release build.
        sb.append("DEV_BUILD=\n");
    }

    new File(projectDir, "build.properties").text = sb.toString()
}

// Transfers the values set in settings.gradle to the rest of the project
project.gradle.ext.getProperties().each { prop ->
    rootProject.ext.set(prop.key, prop.value)
}

// Sets up manifold stuff
writeBuildGradlePredefine(rootProject.mcVers, rootProject.mcIndex)

// Sets up the version string (the name we use for our jar)
rootProject.versionStr = rootProject.mod_version + "-" + rootProject.file_name

subprojects { p ->
    // Apply plugins
    apply plugin: "java"
    apply plugin: "com.gradleup.shadow"
    apply plugin: "systems.manifold.manifold-gradle-plugin"
    apply plugin: "me.modmuss50.mod-publish-plugin"

    project.ext.mainJarTask = {
        return tasks.findByName("remapJar") ?: tasks.getByName("jar")
    }

    project.ext.modDep = { String notation, config = null ->
        def configName = configurations.findByName("modImplementation") ? "modImplementation" : "implementation"
        if (config != null) {
            dependencies.add(configName, notation, config)
        } else {
            dependencies.add(configName, notation)
        }
    }

    project.ext.modCompileDep = { String notation, config = null ->
        def configName = configurations.findByName("modCompileOnly") ? "modCompileOnly" : "compileOnly"
        if (config != null) {
            dependencies.add(configName, notation, config)
        } else {
            dependencies.add(configName, notation)
        }
    }

    project.ext.modApiDep = { String notation, config = null ->
        def configName = configurations.findByName("modApi") ? "modApi" : "api"
        if (config != null) {
            dependencies.add(configName, notation, config)
        } else {
            dependencies.add(configName, notation)
        }
    }


    // Set the manifold version (may not be required tough)
    manifold {
        manifoldVersion = rootProject.manifold_version
    }


    // set up custom configurations (configurations are a way to handle dependencies)
    configurations {
        //// extends the shadowJar configuration
        //shadowMe
        //// have implemented dependencies automatically embedded in the final jar
        //implementation.extendsFrom(shadowMe)


        if (p != project(":common")) {
            // Shadow common
            common
            shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
            compileClasspath.extendsFrom common
            runtimeClasspath.extendsFrom common
            //if (findProject(":forge"))
            //    developmentForge.extendsFrom common
            //if (findProject(":neoforge"))
            //    developmentNeoForge.extendsFrom common
        }
    }


    dependencies {
        annotationProcessor("systems.manifold:manifold-preprocessor:${rootProject.manifold_version}")

        // Add common
        //if (p != project(":common")) {
        //    // Common
        //    common(project(":common")) { transitive false }
        //    shadowCommon(project(":common")) { transitive false }
        //}
    }
    afterEvaluate {
        if (p != project(":common")) {
            dependencies {
                add("common", project(":common")) { transitive = false }
                add("shadowCommon", project(":common")) { transitive = false }
            }
        }
    }


    shadowJar {
        zip64 = true
        //configurations = [project.configurations.shadowMe]
        if (p != project(":common")) {
            configurations.add(project.configurations.shadowCommon) // Shadow the common subproject
            //FIXME relocate "de.the_build_craft.example_mod.common", "loaderCommon.${p.name}.de.the_build_craft.example_mod.common" // Move the loader files to a different location
        }
        def librariesLocation = rootProject.mod_id + ".libraries"

        mergeServiceFiles()
    }
    // Using jar.finalizedBy(shadowJar) causes issues so we do this scuffed bypass
    jar.dependsOn(shadowJar)


    // Put stuff from gradle.properties into the mod info
    processResources {
        def resourceTargets = [ // Location of where to inject the properties

                                // Properties for each of the loaders
                                "fabric.mod.json",
                                "META-INF/mods.toml",
                                "META-INF/neoforge.mods.toml",//for MC >= 1.20.5
                                "pack.mcmeta",

                                // The mixins for each of the loaders
                                rootProject.mod_id + "." + p.name + ".mixins.json"
        ]
        def intoTargets = ["$layout.buildDirectory/resources/main/"] // Location of the built resources folder

        // Fix forge version numbering system as it is weird
        // For whatever reason forge uses [1.18, 1.18.1, 1.18.2) instead of the standard ["1.18", "1.18.1", "1.18.2"]
        def compatible_forgemc_versions = rootProject.hasProperty("compatible_minecraft_versions_neoforge") ? compatible_minecraft_versions_neoforge : "${compatible_minecraft_versions}".replaceAll("\"", "").replaceAll("]", ",)")

        // The left side is what gets replaced in the mod info and the right side is where to get it from in the gradle.properties
        def replaceProperties = [
                mod_id                       : mod_id,
                version                      : mod_version,
                mod_name                     : mod_name,
                group                        : maven_group,
                authors                      : mod_authors,
                description                  : mod_description,
                homepage                     : mod_homepage,
                source                       : mod_source,
                issues                       : mod_issues,
                mod_license                  : mod_license,
                neoforgeUpdateJSONURL        : neoforgeUpdateJSONURL,
                forgeUpdateJSONURL           : forgeUpdateJSONURL,

                minecraft_version            : minecraft_version,
                compatible_minecraft_versions: compatible_minecraft_versions,
                compatible_minecraft_versions_fabric: rootProject.hasProperty("compatible_minecraft_versions_fabric") ? compatible_minecraft_versions_fabric : compatible_minecraft_versions,
                compatible_forgemc_versions  : compatible_forgemc_versions,
                java_version                 : java_version,

                cloth_config_api_fabric_mod_id: getFabricClothConfigModId(),
                cloth_config_api_neoforge_mod_id: getNeoForgeClothConfigModId(),
                cloth_config_api_forge_mod_id: getForgeClothConfigModId(),

                fabric_incompatibility_list  : fabric_incompatibility_list,
                fabric_recommend_list        : fabric_recommend_list,
        ]
        
        // replace any properties in the sub-projects with the values defined here
        inputs.properties replaceProperties
        //replaceProperties.put "project", project
        filesMatching(resourceTargets) {
            expand replaceProperties
        }
        
        intoTargets.each { target ->
            if (file(target).exists()) {
                copy {
                    from(sourceSets.main.resources) {
                        include resourceTargets
                        expand replaceProperties
                    }
                    into target
                }
            }
        }



        // ==================== Delete un-needed files ====================
        exclude "*.${rootProject.mod_id}.accesswidener"
        exclude "*.${rootProject.mod_id}.accesstransformer.cfg"
    }
}

allprojects { p ->
    apply plugin: "java"
    apply plugin: "base"
    apply plugin: "maven-publish"

    base {
        archivesName = rootProject.mod_id
    }
    version = project.name + "-" + rootProject.versionStr
    group = rootProject.maven_group

    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = "Fabric"
                    url = "https://maven.fabricmc.net/"
                }
            }
            filter {
                includeGroupAndSubgroups("net.fabricmc")
                includeGroupAndSubgroups("fabric-loom")
                includeGroupByRegex(".*cuchaz.*")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "NeoForge Releases"
                    url = "https://maven.neoforged.net/releases/"
                }
            }
            forRepository {
                maven {
                    name = "NeoForge Snapshots"
                    url = "https://maven.neoforged.net/snapshots/"
                }
            }
            forRepository {
                maven {
                    name = "NeoForge Mojang Meta"
                    url = "https://maven.neoforged.net/mojang-meta/"
                }
            }
            filter {
                includeGroupByRegex(".*neoforge.*")
                includeGroupAndSubgroups("net.neoforged")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "NeoForge Releases"
                    url = "https://maven.neoforged.net/releases/"
                }
            }
            forRepository {
                maven {
                    name = "NeoForge Snapshots"
                    url = "https://maven.neoforged.net/snapshots/"
                }
            }
            forRepository {
                maven {
                    name = 'Forge'
                    url = uri('https://maven.minecraftforge.net')
                }
            }
            filter {
                includeGroupByRegex(".*minecraftforge.*")
                includeGroupAndSubgroups("net.minecraftforge")
                includeGroupByRegex(".*cpw.*")
                includeGroupByRegex(".*oceanlabs.*")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Sponge"
                    url = "https://repo.spongepowered.org/repository/maven-public/"
                }
            }
            filter {
                includeGroupAndSubgroups("org.spongepowered")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "ParchmentMC"
                    url = "https://maven.parchmentmc.org"
                }
            }
            filter {
                includeGroupAndSubgroups("org.parchmentmc")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Modrinth"
                    url = "https://api.modrinth.com/maven"
                }
            }
            filter {
                includeGroupAndSubgroups("maven.modrinth")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Terraformers (ModMenu)"
                    url = "https://maven.terraformersmc.com/"
                }
            }
            filter {
                includeGroupAndSubgroups("com.terraformersmc")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Shedaniel (ClothConfig)"
                    url = "https://maven.shedaniel.me/"
                }
            }
            filter {
                includeGroupAndSubgroups("me.shedaniel")
            }
        }
        exclusiveContent {
            forRepository {
                maven {
                    name = "Xaero"
                    url = "https://chocolateminecraft.com/maven"
                }
            }
            filter {
                includeGroupAndSubgroups("xaero")
            }
        }
        //maven {
        //    name = "JitPack"
        //    url = "https://jitpack.io"
        //    content {
        //        includeGroupByRegex "com\\.github\\..*"
        //        includeGroupByRegex "io\\.github\\..*"
        //    }
        //}
        maven {
            name = "Sonatype Snapshots"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
            content {
                includeGroupAndSubgroups("systems.manifold")
            }
        }

        flatDir {
            dirs "${rootDir}/mods/fabric"
            content { includeGroup "fabric-mod" }
        }
        flatDir {
            dirs "${rootDir}/mods/quilt"
            content { includeGroup "quilt-mod" }
        }
        flatDir {
            dirs "${rootDir}/mods/forge"
            content { includeGroup "forge-mod" }
        }
        flatDir {
            dirs "${rootDir}/mods/neoforge"
            content { includeGroup "neoforge-mod" }
        }

        mavenCentral()
    }

    tasks.register("copyCommonLoaderResources", Copy) {
        from project(":common").file("src/main/resources/${accessWidenerVersion}.${rootProject.mod_id}.accesswidener")
        into(file(p.file("build/resources/main")))
        rename "${accessWidenerVersion}.${rootProject.mod_id}.accesswidener", "${rootProject.mod_id}.accesswidener"
    }

    tasks.register("copyAccesstransformerResources", Copy) {
        from project(":common").file("src/main/resources/${accessWidenerVersion}.${rootProject.mod_id}.accesstransformer.cfg")
        into(file(p.file("build/resources/main/META-INF")))
        rename "${accessWidenerVersion}.${rootProject.mod_id}.accesstransformer.cfg", "accesstransformer.cfg"
    }

    tasks.register("copyCoreResources", Copy) {
        from fileTree(project(":common").file("src/main/resources/assets"))
        into p.file("build/resources/main/assets")
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = rootProject.java_version as Integer
        options.compilerArgs += ["-Xplugin:Manifold"]
        options.encoding = "UTF-8"
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version)
        //withSourcesJar()
    }
}

def getFabricClothConfigModId(){
    if (rootProject.hasProperty("cloth_config_api_fabric_mod_id")){
        return cloth_config_api_fabric_mod_id
    }
    else{
        return "cloth-config"
    }
}

def getNeoForgeClothConfigModId(){
    if (rootProject.hasProperty("cloth_config_api_neoforge_mod_id")){
        return cloth_config_api_neoforge_mod_id
    }
    else{
        return "cloth_config"
    }
}

def getForgeClothConfigModId(){
    if (rootProject.hasProperty("cloth_config_api_forge_mod_id")){
        return cloth_config_api_forge_mod_id
    }
    else{
        return "cloth_config"
    }
}
