#!/bin/sh

echo "==================== Note: All build jars will be in the folder called 'buildAllJars' ===================="
rm -rf buildAllJars/*
mkdir -p buildAllJars

for d in versionProperties/*; do
  [ -f "$d" ] || continue

  version=$(basename "$d" .properties)

  echo "==================== Cleaning workspace to build $version ===================="
  ./gradlew clean -PmcVer="$version" --no-daemon || true

  rm -rf fabric/build
  rm -rf forge/build
  rm -rf neoforge/build

  echo "==================== Building $version ===================="
  ./gradlew build -PmcVer="$version" --no-daemon || true

  echo "==================== Copying jars ===================="
  cp fabric/build/libs/*.jar buildAllJars/ 2>/dev/null || true
  cp forge/build/libs/*.jar buildAllJars/ 2>/dev/null || true
  cp neoforge/build/libs/*.jar buildAllJars/ 2>/dev/null || true

  echo "==================== Deleting unnecessary *-all.jars ===================="
  rm -f buildAllJars/*-all.jar
done

echo "================================================================"
echo "=========================== FINISHED ==========================="
echo "================================================================"