# Gradle stuff
org.gradle.jvmargs=-Xmx8192M
org.gradle.parallel=true
org.gradle.caching=true

# Mod Info
## Remember to set the MOD_ID in AbstractModInitializer.java
mod_id=maplink
## Remember to set the VERSION in AbstractModInitializer.java
mod_version=4.5.0
## use topLevelDomain.yourName.modID
maven_group=de.the_build_craft.maplink
## Remember to set the MOD_NAME in AbstractModInitializer.java
mod_name=Map Link
mod_description=Synchronizes player positions, marker positions and area overlays from Bluemap, Dynmap, Pl3xMap or Squaremap with Xaero's Minimap and Worldmap. Also displays AFK time in the tab list.
mod_license=GPL-3
# Note: In forge's mods.toml this is hard coded because Architectury throws an error with setting it as a variable
mod_authors=["the_build_craft"]
mod_homepage=https://modrinth.com/mod/maplink
mod_source=https://github.com/thebuildcraft/MapLink
mod_issues=https://github.com/thebuildcraft/MapLink/issues
forgeUpdateJSONURL=https://api.modrinth.com/updates/kiByZ6gx/forge_updates.json
neoforgeUpdateJSONURL=https://api.modrinth.com/updates/kiByZ6gx/forge_updates.json?neoforge=only

# Global Plugin Versions
manifold_version=2026.1.7

# Global Mod Config
default_xaeros_minimap_version=26.4.2
default_xaeros_worldmap_version=1.44.2

enable_xaeros_minimap=true
enable_xaeros_worldmap=true

# Internal Properties (These are set at runtime for Forgix to merge jar's)
versionStr=

# This defines what MC version Intellij will use for the preprocessor
# and what version is used automatically by build and run commands
mcVer=26.2.0

# Publishing information
# can be changed per version with "fabric_is_quilt_compatible" in version properties
default_quilt_compatibility=true
publish_debug_mode=false
modrinth_id=kiByZ6gx
publish_to_modrinth=true
curseforge_id=
publish_to_curseforge=false
# Type of release: "alpha", "beta" or "stable"
release_type=stable
# Curseforge Environment tag: "server", "client" or "both"
curse_environment=client

# Defines the maximum amount of memory Minecraft is allowed when run in a development environment
#minecraftMemoryJavaArg="-Xmx4G"
