/*
 *    This file is part of the Map Link mod
 *    licensed under the GNU GPL v3 License.
 *    (some parts of this file are originally from the Distant Horizons mod by James Seibel)
 *
 *    Copyright (C) 2024 - 2026  Leander Knüttel and contributors
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * file changed by: Leander Knüttel
 * date: 06.08.2026
 */

plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.143'
}

legacyForge {
    version = "${rootProject.minecraft_version}-${rootProject.forge_version}"

    def at = file("src/main/resources/${accessWidenerVersion}.${mod_id}.accesstransformer.cfg")
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    validateAccessTransformers = true

    //runs {
    //    client {
    //        client()
    //    }
    //    data {
    //        data()
    //    }
    //    server {
    //        server()
    //    }
    //}
//

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

//sourceSets {
//    commonSource {
//        java {
//            srcDirs = [project(':common').file('src/main/java')]
//        }
//    }
//}

mixin {
    add sourceSets.main, "${mod_id}.forge.mixins.refmap.json"
    //add sourceSets.commonSource, "${mod_id}.forge.mixins.refmap.json"
    config "${mod_id}.forge.mixins.json"
}

mainJarTask().configure {
    if (it.hasProperty('inputFile')) {
        it.inputFile = shadowJar.archiveFile
    }
    else {
        from(zipTree(shadowJar.archiveFile)) {
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }
    }
    dependsOn shadowJar
//    classifier null

    //accessTransformers.add("${rootProject.mod_id}.accesstransformer.cfg")
    manifest.attributes([
            "MixinConfigs": "${mod_id}.forge.mixins.json"
    ])
}

obfuscation {
    reobfuscate(tasks.named('shadowJar'), sourceSets.main)
}

configurations {
    // The addModJar basically embeds the mod to the built jar
    addModJar
    include.extendsFrom addModJar
    modImplementation.extendsFrom addModJar
}

def addMod(path, enabled) {
    if (enabled == "2")
        dependencies { modImplementation(path) }
    else if (enabled == "1")
        dependencies { modCompileOnly(path) }
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.3"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.3"))
    modApi "me.shedaniel.cloth:cloth-config-forge:${rootProject.cloth_config_api_forge_version}"

    if (rootProject.enable_xaeros_minimap == "true") {
        if (rootProject.hasProperty("xaeros_minimap_forge_version") && rootProject.xaeros_minimap_forge_version != "") {
            modImplementation "xaero.minimap:xaerominimap-forge-${rootProject.minecraft_version}:${rootProject.xaeros_minimap_forge_version}"
        } else {
            modImplementation "xaero.minimap:xaerominimap-forge-${rootProject.minecraft_version}:${rootProject.default_xaeros_minimap_version}"
        }
    } else {
        if (rootProject.hasProperty("xaeros_minimap_forge_version") && rootProject.xaeros_minimap_forge_version != "") {
            modCompileOnly "xaero.minimap:xaerominimap-forge-${rootProject.minecraft_version}:${rootProject.xaeros_minimap_forge_version}"
        } else {
            modCompileOnly "xaero.minimap:xaerominimap-forge-${rootProject.minecraft_version}:${rootProject.default_xaeros_minimap_version}"
        }
    }
    if (rootProject.enable_xaeros_worldmap == "true") {
        if (rootProject.hasProperty("xaeros_worldmap_forge_version") && rootProject.xaeros_worldmap_forge_version != "") {
            modImplementation "xaero.map:xaeroworldmap-forge-${rootProject.minecraft_version}:${rootProject.xaeros_worldmap_forge_version}"
        } else {
            modImplementation "xaero.map:xaeroworldmap-forge-${rootProject.minecraft_version}:${rootProject.default_xaeros_worldmap_version}"
        }
    } else {
        if (rootProject.hasProperty("xaeros_worldmap_forge_version") && rootProject.xaeros_worldmap_forge_version != "") {
            modCompileOnly "xaero.map:xaeroworldmap-forge-${rootProject.minecraft_version}:${rootProject.xaeros_worldmap_forge_version}"
        } else {
            modCompileOnly "xaero.map:xaeroworldmap-forge-${rootProject.minecraft_version}:${rootProject.default_xaeros_worldmap_version}"
        }
    }
    modCompileOnly "xaero.lib:xaerolib-forge-${rootProject.minecraft_version}:${rootProject.xaero_lib_version}"
}

tasks.register('deleteResources', Delete) {
    delete file("build/resources/main")
}

tasks.register('copyAllResources') {
    dependsOn(tasks.named("copyCoreResources"))
    //dependsOn(tasks.named("copyCommonLoaderResources"))
    dependsOn(tasks.named("copyAccesstransformerResources"))
}

processResources {
    dependsOn(tasks.named('copyAllResources'))
    exclude "*.accesswidener"
}

publishMods {
    file = mainJarTask().archiveFile
    dryRun = publish_debug_mode.toBoolean()
    changelog = file("$rootDir/docs/changelogs/${mod_version}.md").text.trim()
    switch (release_type) {
        case "alpha":
            type = ALPHA
            break
        case "beta":
            type = BETA
            break
        case "stable":
            type = STABLE
            break
    }

    displayName = "[Forge | ${rootProject.file_name}] ${mod_version}"

    modLoaders.add("forge")

    String gameVersionsString = rootProject.compatible_minecraft_versions
    String[] gameVersions = gameVersionsString.replace("[", "").replace("]", "").replaceAll(" ", "").replaceAll("\"", "").split(",")

    if (publish_to_modrinth.toBoolean()) {
        modrinth {
            accessToken = providers.environmentVariable("MODRINTH_TOKEN")
            projectId = modrinth_id
            minecraftVersions.addAll(gameVersions)

            requires("cloth-config")
            optional("xaeros-minimap", "xaeros-minimap-fair", "xaeros-world-map")
        }
    }

    if (publish_to_curseforge.toBoolean()) {
        curseforge {
            accessToken = providers.environmentVariable("CURSE_TOKEN")
            projectId = curseforge_id
            if (curse_environment == "both" || curse_environment == "server") serverRequired = true
            if (curse_environment == "both" || curse_environment == "client") clientRequired = true
            minecraftVersions.addAll(gameVersions)

            requires("cloth-config")
            optional("xaeros-minimap", "xaeros-minimap-fair-play-edition", "xaeros-world-map")
        }
    }
}
