/*
 *    This file is part of the Map Link mod
 *    licensed under the GNU GPL v3 License.
 *
 *    Copyright (C) 2024 - 2026  Leander Knüttel and contributors
 *
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * by: Leander Knüttel
 * date: 15.02.2026
 */

architectury {
    common(((String) gradle.builds_for).split(","))
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    if (rootProject.hasProperty("xaero_no_common") && rootProject.xaero_no_common == "true") {
        if (rootProject.hasProperty("xaeros_minimap_fabric_version") && rootProject.xaeros_minimap_fabric_version != "") {
            compileOnly "xaero.minimap:xaerominimap-fabric-${rootProject.minecraft_version}:${rootProject.xaeros_minimap_fabric_version}"
        } else {
            compileOnly "xaero.minimap:xaerominimap-fabric-${rootProject.minecraft_version}:${rootProject.default_xaeros_minimap_version}"
        }
        if (rootProject.hasProperty("xaeros_worldmap_fabric_version") && rootProject.xaeros_worldmap_fabric_version != "") {
            compileOnly "xaero.map:xaeroworldmap-fabric-${rootProject.minecraft_version}:${rootProject.xaeros_worldmap_fabric_version}"
        } else {
            compileOnly "xaero.map:xaeroworldmap-fabric-${rootProject.minecraft_version}:${rootProject.default_xaeros_worldmap_version}"
        }
    } else {
        if (rootProject.hasProperty("xaeros_minimap_fabric_version") && rootProject.xaeros_minimap_fabric_version != "") {
            compileOnly "xaero.minimap:xaerominimap-common-${rootProject.minecraft_version}:${rootProject.xaeros_minimap_fabric_version}"
        } else {
            compileOnly "xaero.minimap:xaerominimap-common-${rootProject.minecraft_version}:${rootProject.default_xaeros_minimap_version}"
        }
        if (rootProject.hasProperty("xaeros_worldmap_fabric_version") && rootProject.xaeros_worldmap_fabric_version != "") {
            compileOnly "xaero.map:xaeroworldmap-common-${rootProject.minecraft_version}:${rootProject.xaeros_worldmap_fabric_version}"
        } else {
            compileOnly "xaero.map:xaeroworldmap-common-${rootProject.minecraft_version}:${rootProject.default_xaeros_worldmap_version}"
        }
    }

    implementation "me.shedaniel.cloth:cloth-config-fabric:${rootProject.cloth_config_api_fabric_version}"
}

