# 1.21.11 version
java_version=21
minecraft_version=1.21.11
neo_form_version=1.21.11-20251209.172050
parchment_minecraft=1.21.11
parchment_version=2025.12.20
compatible_minecraft_versions=["1.21.11"]
accessWidenerVersion=1_21_6
file_name=1.21.11
builds_for=fabric,neoforge

xaero_lib_version=1.7.1
asm_version=9.9

# Fabric loader
fabric_loader_version=0.19.3
fabric_api_version=0.141.6+1.21.11
    # Fabric mod versions
    modmenu_version=17.0.0
    cloth_config_api_fabric_version=21.11.153

    #{ "some_mod": "*" }
    fabric_incompatibility_list={}
    fabric_recommend_list={}

# NeoForge loader
neoforge_version=21.11.45
    # NeoForge mod versions
    cloth_config_api_neoforge_version=21.11.153
