# 26.1 version
java_version=25
minecraft_version=26.1.2
neo_form_version=26.1.2-1
compatible_minecraft_versions=["26.1", "26.1.1", "26.1.2"]
compatible_minecraft_versions_fabric="~26.1"
compatible_minecraft_versions_neoforge=[26.1,26.2)
accessWidenerVersion=26_1
file_name=26.1
builds_for=fabric,neoforge

xaero_lib_version=1.7.1
asm_version=9.9

# Fabric loader
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2
    # Fabric mod versions
    modmenu_version=18.0.0
    cloth_config_api_fabric_version=26.1.154
    #xaeros_minimap_fabric_version=25.3.11
    #xaeros_worldmap_fabric_version=1.40.14

    fabric_incompatibility_list={}
    fabric_recommend_list={}

# NeoForge loader
neoforge_version=26.1.2.93
    # NeoForge mod versions
    cloth_config_api_neoforge_version=26.1.154
    #xaeros_minimap_neoforge_version=25.3.11
    #xaeros_worldmap_neoforge_version=1.40.15
