# 26.1.2 version
java_version=25
minecraft_version=26.1.2
compatible_minecraft_versions=["26.1.2"]
accessWidenerVersion=26_1_2
file_name=26.1.2
builds_for=fabric,neoforge

xaero_lib_version=1.1.11

# Fabric loader
fabric_loader_version=0.19.2
fabric_api_version=0.149.1+26.1.2
    # Fabric mod versions
    modmenu_version=19.0.0-alpha.1
    cloth_config_api_fabric_version=26.1.154

    #{ "some_mod": "*" }
    fabric_incompatibility_list={}
    fabric_recommend_list={}

# NeoForge loader
neoforge_version=26.1.2.64-beta
    # NeoForge mod versions
    cloth_config_api_neoforge_version=26.1.154
